name: Check dependency releases

on:
  schedule:
    - cron: '0 6,18 * * *'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  check-elegant-common:
    uses: tiobe/public-workflows/.github/workflows/elegant-checkers-dependency-check.yml@v1.0.2
    with:
      dependency-name: elegant-common
    secrets:
      deploy-key: ${{ secrets.ELEGANT_COMMON_DEPLOY_KEY }}
      gh-pat: ${{ secrets.GH_PAT }}

  check-elegant-sdk:
    uses: tiobe/public-workflows/.github/workflows/elegant-checkers-dependency-check.yml@v1.0.2
    with:
      dependency-name: elegant-sdk
    secrets:
      deploy-key: ${{ secrets.ELEGANT_SDK_DEPLOY_KEY }}
      gh-pat: ${{ secrets.GH_PAT }}
