name: Check elegant-common release

on:
  schedule:
    - cron: '0 6,18 * * *'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  check:
    uses: tiobe/public-workflows/.github/workflows/elegant-checkers-check-elegant-common-release.yml@cdf48792866f0f69c0743041b1558522e3228408 # v1.0.0
    secrets: inherit
