name: Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      ref: ${{ github.event.release.tag_name }}
      package: true
    secrets: inherit

  publish:
    needs: build
    uses: tiobe/public-workflows/.github/workflows/release-publish.yml@v1.0.0
    with:
      product-name: GawlKeeper
      semver: ${{ needs.build.outputs.semver }}
    secrets: inherit
